### PR TITLE
Added Docs folder

### PR DESCRIPTION
**Pull request by AwesomeCronk**
Everything there is in Markdown for now.

### CODE REVIEW

**Comment by dawnofmidnight** [comment]
Do you want to write the intro section for the docs and put it in? Also, we might want to divide up the docs later, but this is good for now.

**Comment by AwesomeCronk** [comment]
Definitely will. I'll put it in index.md.

**Comment by dawnofmidnight** [comment]
Sounds good!

**Comment by AwesomeCronk** [comment]
I added a ton of syntax docs.

**Comment by AwesomeCronk** [comment]
Now includes docs on math operators.

**Comment by dawnofmidnight** [comment]
Thank you! We can divide it up later.

**Pull request merged**
