### PR TITLE
Hopefully made it more flexible. There's a 99% chance I messed up :( Review before merging

### PR DESCRIPTION
**Pull request by Arghya-AB**
The repl now does continuous prompts. Added a few parameters for more flexibility (hopefully)

### CODE REVIEW

**Review by AbooMinister25 — APPROVED** [review]
Alright, this seems pretty good, doesn't seem like it'll break it lol.

**Review by dawnofmidnight — APPROVED** [review]
Looks good to me. But I'm not a d.py expert, so I'll see if we can get one more approval before I go ahead and merge.

**Comment by dawnofmidnight** [comment]
@Arghya-AB Can you fix the conflicts that came with the recent PR?

**Comment by dawnofmidnight** [comment]
It still says there are conflicts.

**Pull request closed without merging**
